#!/bin/bash
# file to clear axis info using M110
halcmd setp axisui.notifications-clear 0
sleep .200
halcmd setp axisui.notifications-clear 1
sleep .200
halcmd setp axisui.notifications-clear 0
exit 0