#!/bin/bash
# file to clear axis all
halcmd setp axisui.notifications-clear-all 0
sleep .200
halcmd setp axisui.notifications-clear-all 1
sleep .200
halcmd setp axisui.notifications-clear-all 0
exit 0