#!/bin/bash
# file to clear axis error
halcmd setp axisui.notifications-clear-error 0
sleep .200
halcmd setp axisui.notifications-clear-error 1
sleep .200
halcmd setp axisui.notifications-clear-error 0
exit 0